<?php

namespace App\Console\Commands;

use App\Services\Updates\ReleasePublisher;
use Illuminate\Console\Command;

/**
 * oeparts:release:manifest (Module 21, Chunk 5.2) — after build/build.sh produces the
 * zip + dist/build-result.json, this folds the zip's sha256/size/download-url into
 * version.json and upserts the entry into the releases.json catalog. The CI workflow
 * runs it on a v*.*.* tag, then publishes both files (raw on main + Release assets).
 */
class GenerateReleaseManifest extends Command
{
    protected $signature = 'oeparts:release:manifest
        {--version-file= : Path to version.json (default: base path)}
        {--catalog-file= : Path to releases.json (default: base path)}
        {--build-result= : Path to dist/build-result.json (default: base path)}
        {--json : Emit a machine-readable summary}';

    protected $description = 'Fold the build result into version.json and upsert the releases.json catalog.';

    public function handle(ReleasePublisher $publisher): int
    {
        $versionFile = (string) ($this->option('version-file') ?: base_path('version.json'));
        $catalogFile = (string) ($this->option('catalog-file') ?: base_path('releases.json'));
        $buildFile   = (string) ($this->option('build-result') ?: base_path('dist/build-result.json'));

        $manifest = $this->readJson($versionFile);
        if ($manifest === null) {
            $this->error('version.json not found or invalid: '.$versionFile);

            return self::FAILURE;
        }

        $build = $this->readJson($buildFile);
        if ($build === null) {
            $this->error('build result not found or invalid: '.$buildFile.' (run build/build.sh first).');

            return self::FAILURE;
        }

        if (($build['version'] ?? null) !== ($manifest['version'] ?? null)) {
            $this->error('Version mismatch: version.json is '.($manifest['version'] ?? '?')
                .' but the build is '.($build['version'] ?? '?').'.');

            return self::FAILURE;
        }

        $manifest = $publisher->finalize($manifest, $build);
        $this->writeJson($versionFile, $manifest);

        $catalog = $this->readJson($catalogFile) ?? [
            '_comment' => 'Ordered catalog of all published releases. Newest first. Generated by oeparts:release:manifest.',
            'channel'  => $manifest['channel'] ?? 'stable',
            'latest'   => null,
            'releases' => [],
        ];
        $catalog = $publisher->upsert($catalog, $manifest);
        $this->writeJson($catalogFile, $catalog);

        if ($this->option('json')) {
            $this->line((string) json_encode([
                'success'      => true,
                'version'      => $manifest['version'],
                'sha256'       => $manifest['sha256'],
                'size_bytes'   => $manifest['size_bytes'],
                'download_url' => $manifest['download_url'],
                'latest'       => $catalog['latest'],
                'release_count' => count($catalog['releases']),
            ], JSON_UNESCAPED_SLASHES));

            return self::SUCCESS;
        }

        $this->info('Release manifest generated for v'.$manifest['version']);
        $this->line('  sha256:       '.$manifest['sha256']);
        $this->line('  size_bytes:   '.$manifest['size_bytes']);
        $this->line('  download_url: '.$manifest['download_url']);
        $this->line('  catalog latest: '.$catalog['latest'].' ('.count($catalog['releases']).' releases)');

        return self::SUCCESS;
    }

    /** @return array<string,mixed>|null */
    private function readJson(string $path): ?array
    {
        if (! is_file($path)) {
            return null;
        }
        $data = json_decode((string) @file_get_contents($path), true);

        return is_array($data) ? $data : null;
    }

    private function writeJson(string $path, array $data): void
    {
        file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL);
    }
}
