<?php

namespace App\Console\Commands;

use App\Services\Updates\ReleasePublisher;
use App\Services\Updates\ReleaseSignature;
use Illuminate\Console\Command;

/**
 * oeparts:release:manifest (Module 21, Chunk 5.2) — after build/build.sh produces the
 * zip + dist/build-result.json, this folds the zip's sha256/size/download-url into
 * version.json and upserts the entry into the releases.json catalog. The CI workflow
 * runs it on a v*.*.* tag, then publishes both files (raw on main + Release assets).
 */
class GenerateReleaseManifest extends Command
{
    protected $signature = 'oeparts:release:manifest
        {--version-file= : Path to version.json (default: base path)}
        {--catalog-file= : Path to releases.json (default: base path)}
        {--build-result= : Path to dist/build-result.json (default: base path)}
        {--private-key= : PEM release signing key (overrides OE_RELEASE_PRIVATE_KEY)}
        {--git-commit-sha= : Commit SHA this release tag points at (default: `git rev-parse HEAD` in the CWD, which the CI workflow runs this command from already checked out at the release tag)}
        {--json : Emit a machine-readable summary}';

    protected $description = 'Fold the build result into version.json, sign it, and upsert the releases.json catalog.';

    public function handle(ReleasePublisher $publisher, ReleaseSignature $signer): int
    {
        $versionFile = (string) ($this->option('version-file') ?: base_path('version.json'));
        $catalogFile = (string) ($this->option('catalog-file') ?: base_path('releases.json'));
        $buildFile   = (string) ($this->option('build-result') ?: base_path('dist/build-result.json'));

        $manifest = $this->readJson($versionFile);
        if ($manifest === null) {
            $this->error('version.json not found or invalid: '.$versionFile);

            return self::FAILURE;
        }

        $build = $this->readJson($buildFile);
        if ($build === null) {
            $this->error('build result not found or invalid: '.$buildFile.' (run build/build.sh first).');

            return self::FAILURE;
        }

        if (($build['version'] ?? null) !== ($manifest['version'] ?? null)) {
            $this->error('Version mismatch: version.json is '.($manifest['version'] ?? '?')
                .' but the build is '.($build['version'] ?? '?').'.');

            return self::FAILURE;
        }

        $manifest = $publisher->finalize($manifest, $build);

        // Sign the release (version + sha256) if a private key is available. Verification
        // against the app-baked public key happens at pre-flight on every install (6.1).
        $privateKey = $this->resolvePrivateKey();
        if ($privateKey !== null) {
            $manifest['signature'] = $signer->sign($signer->payloadFor($manifest), $privateKey);
            $this->info('Release signed.');
        } else {
            $this->warn('No release signing key — publishing UNSIGNED (set OE_RELEASE_PRIVATE_KEY to sign).');
        }

        // The zip signature above proves nothing about what a git-managed
        // install's `git checkout` pulls down — that path never touches the
        // zip at all. Separately bind + sign this release's commit SHA so
        // PreflightService::checkSignature() can catch a compromised or
        // re-pushed git remote tag (see ReleaseSignature::verifyGitManifest()).
        $commitSha = $this->resolveGitCommitSha();
        if ($commitSha !== null) {
            $manifest['git_commit_sha'] = $commitSha;
            if ($privateKey !== null) {
                $manifest['git_signature'] = $signer->sign($signer->gitPayloadFor($manifest), $privateKey);
            }
        } else {
            $this->warn('Could not determine the git commit SHA for this release — git-managed installs '.
                'will fail the signature pre-flight check if signing is enforced (OE_RELEASE_PUBLIC_KEY set).');
        }

        $this->writeJson($versionFile, $manifest);

        $catalog = $this->readJson($catalogFile) ?? [
            '_comment' => 'Ordered catalog of all published releases. Newest first. Generated by oeparts:release:manifest.',
            'channel'  => $manifest['channel'] ?? 'stable',
            'latest'   => null,
            'releases' => [],
        ];
        $catalog = $publisher->upsert($catalog, $manifest);
        $this->writeJson($catalogFile, $catalog);

        if ($this->option('json')) {
            $this->line((string) json_encode([
                'success'      => true,
                'version'      => $manifest['version'],
                'sha256'       => $manifest['sha256'],
                'size_bytes'   => $manifest['size_bytes'],
                'signed'       => ! empty($manifest['signature']),
                'download_url' => $manifest['download_url'],
                'latest'       => $catalog['latest'],
                'release_count' => count($catalog['releases']),
            ], JSON_UNESCAPED_SLASHES));

            return self::SUCCESS;
        }

        $this->info('Release manifest generated for v'.$manifest['version']);
        $this->line('  sha256:       '.$manifest['sha256']);
        $this->line('  size_bytes:   '.$manifest['size_bytes']);
        $this->line('  download_url: '.$manifest['download_url']);
        $this->line('  catalog latest: '.$catalog['latest'].' ('.count($catalog['releases']).' releases)');

        return self::SUCCESS;
    }

    /** The signing key, from --private-key (a PEM string or a file path) or config/env. */
    private function resolvePrivateKey(): ?string
    {
        $opt = (string) ($this->option('private-key') ?: '');
        if ($opt !== '') {
            if (is_file($opt)) {
                $contents = @file_get_contents($opt);

                // file_get_contents() failing (permissions, transient I/O
                // error) previously fell through as an empty string, which
                // still looks like "a key was provided" to the caller —
                // openssl_pkey_get_private('') then fails and throws,
                // crashing the release build instead of taking the intended
                // "publish UNSIGNED" fallback below.
                return $contents !== false && $contents !== '' ? $contents : null;
            }

            return $opt;
        }

        $key = trim((string) config('updates.signing.private_key', ''));

        return $key !== '' ? $key : null;
    }

    /** The commit SHA this release tag points at — from --git-commit-sha, or `git rev-parse HEAD` in the CWD. */
    private function resolveGitCommitSha(): ?string
    {
        $opt = trim((string) ($this->option('git-commit-sha') ?: ''));
        if ($opt !== '') {
            return $opt;
        }

        $process = new \Symfony\Component\Process\Process(['git', 'rev-parse', 'HEAD']);
        $process->run();

        return $process->isSuccessful() ? trim($process->getOutput()) : null;
    }

    /** @return array<string,mixed>|null */
    private function readJson(string $path): ?array
    {
        if (! is_file($path)) {
            return null;
        }
        $data = json_decode((string) @file_get_contents($path), true);

        return is_array($data) ? $data : null;
    }

    private function writeJson(string $path, array $data): void
    {
        file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL);
    }
}
